import img1 from "../assets/men-01.jpg";
import img2 from "../assets/men-02.jpg";
import img3 from "../assets/men-03.jpg";
import img4 from "../assets/women-01.jpg";
import img5 from "../assets/women-02.jpg";

const fakeData = [
    {
      id: "1",
      img:img1,
      name: "John Doe",
      email: "johndoe@example.com",
      status: "Active",
      role: "Admin",
      createdAt: "2024-03-15",
    },
    {
      id: "2",
      img: img2,
      name: "Jane Smith",
      email: "janesmith@example.com",
      status: "Queued",
      role: "User",
      createdAt: "2024-03-16",
    },
    {
      id: "3",
      img: img3,
      name: "Michael Brown",
      email: "michaelbrown@example.com",
      status: "Validated",
      role: "Moderator",
      createdAt: "2024-03-17",
    },
    {
      id: "4",
      img: img4,
      name: "Emily White",
      email: "emilywhite@example.com",
      status: "InActive",
      role: "User",
      createdAt: "2024-03-18",
    },
    {
      id: "5",
      img: img5,
      name: "Chris Johnson",
      email: "chrisjohnson@example.com",
      status: "Scheduled",
      role: "Admin",
      createdAt: "2024-03-19",
    },
    {
      id: "6",
      img: img2,
      name: "Jane Smith",
      email: "janesmith@example.com",
      status: "Queued",
      role: "User",
      createdAt: "2024-03-16",
    },
    {
      id: "7",
      img: img3,
      name: "Michael Brown",
      email: "michaelbrown@example.com",
      status: "Validated",
      role: "Moderator",
      createdAt: "2024-03-17",
    },
    {
      id: "8",
      img: img4,
      name: "Emily White",
      email: "emilywhite@example.com",
      status: "InActive",
      role: "User",
      createdAt: "2024-03-18",
    },
    {
      id: "9",
      img: img5,
      name: "Chris Johnson",
      email: "chrisjohnson@example.com",
      status: "Scheduled",
      role: "Admin",
      createdAt: "2024-03-19",
    },
    {
      id: "10",
      img: img2,
      name: "Jane Smith",
      email: "janesmith@example.com",
      status: "Queued",
      role: "User",
      createdAt: "2024-03-16",
    },
    {
      id: "11",
      img: img3,
      name: "Michael Brown",
      email: "michaelbrown@example.com",
      status: "Validated",
      role: "Moderator",
      createdAt: "2024-03-17",
    },
    {
      id: "12",
      img: img4,
      name: "Emily White",
      email: "emilywhite@example.com",
      status: "InActive",
      role: "User",
      createdAt: "2024-03-18",
    },
    {
      id: "13",
      img: img5,
      name: "Chris Johnson",
      email: "chrisjohnson@example.com",
      status: "Scheduled",
      role: "Admin",
      createdAt: "2024-03-19",
    },
    {
      id: "14",
      img: img2,
      name: "Jane Smith",
      email: "janesmith@example.com",
      status: "Queued",
      role: "User",
      createdAt: "2024-03-16",
    },
    {
      id: "15",
      img: img3,
      name: "Michael Brown",
      email: "michaelbrown@example.com",
      status: "Validated",
      role: "Moderator",
      createdAt: "2024-03-17",
    },
    {
      id: "16",
      img: img4,
      name: "Emily White",
      email: "emilywhite@example.com",
      status: "InActive",
      role: "User",
      createdAt: "2024-03-18",
    },
    {
      id: "17",
      img: img5,
      name: "Chris Johnson",
      email: "chrisjohnson@example.com",
      status: "Scheduled",
      role: "Admin",
      createdAt: "2024-03-19",
    },
  ];
  
  const columns = [
    { key: "img", label: "Image" , isImage: true},
    { key: "name", label: "Name" },
    { key: "email", label: "Email" },
    { key: "status", label: "Status", isStatus: true },
    { key: "role", label: "Role" },
    { key: "createdAt", label: "Created At" },
  ];
  
  export { fakeData, columns };
  